FROM certbot/certbot
RUN apk add --no-cache bash

RUN mkdir -p /etc/letsencrypt

ADD certbot-entrypoint.sh /certbot-entrypoint.sh

RUN chmod +x /certbot-entrypoint.sh

ENTRYPOINT ["/bin/bash", "/certbot-entrypoint.sh"]